# Numpy


## numpy 属性

In [1]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Create a 3x3 array
print(array)
print('number of dimensions:', array.ndim) # Number of dimensions
print('shape of array:', array.shape) # Shape of the array
print('size of array:', array.size) # Total number of elements in the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
number of dimensions: 2
shape of array: (3, 3)
size of array: 9


## 创建 array

In [2]:
a = np.array([2,23,4], dtype=np.float16) # Create an array with specified data type
print(a.dtype) # Check the data type of the array

b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float16) # Create a 3x3 array with specified data type
print(b)

c = np.zeros((2,3)) # Create a 2x3 array filled with zeros
print(c)

d = np.ones((4,2)) # Create a 4x2 array filled with ones
print(d)

e = np.empty((3,3)) # Create a 3x3 array without initializing entries
print(e)

f = np.arange(0,10,2) # Create an array with values from 0 to 10 with a step of 2
print(f)

g = np.arange(12).reshape(3,4) # Create an array with values from 0 to 11 and reshape it to 3x4
print(g)

h = np.linspace(0,1,5).reshape(1,5) # Create an array of 5 evenly spaced values between 0 and 1
print(h)

float16
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[3.89273496e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[0 2 4 6 8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0.   0.25 0.5  0.75 1.  ]]


## 基础运算

In [3]:
a = np.array([10,20,30,40])
b = np.arange(4)

print(a+b)
print(10*np.sin(a)) # Apply sine function to each element of the array
print(a<25) # Element-wise comparison, returns a boolean array  

c = a.reshape(2,2)
d = b.reshape(2,2)
print(np.dot(c,d)) # Matrix multiplication of two 2x2 arrays

print(np.sum(c)) # Sum of all elements in the array
print(np.min(c)) # Minimum value in the array
print(np.max(c)) # Maximum value in the array
print(np.sum(c, axis=0)) # Sum of each column
print(np.sum(c, axis=1)) # Sum of each row

[10 21 32 43]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True False False]
[[ 40  70]
 [ 80 150]]
100
10
40
[40 60]
[30 70]


In [4]:
A = np.arange(2,14).reshape(3,4)

print(np.argmin(A)) # Index of the minimum value in the array
print(np.argmax(A)) # Index of the maximum value in the array
print(np.mean(A)) # Mean of all elements in the array
print(np.median(A)) # Median of all elements in the array
print(np.cumsum(A)) # Cumulative sum of the elements in the array
print(np.diff(A)) # Calculate the n-th discrete difference along the given axis
print(np.nonzero(A)) # Indices of the non-zero elements in the array
print(np.sort(A)) # Sort the array
print(np.transpose(A)) # Transpose of the array
print(np.clip(A, 5, 10)) # Clip the values in the array to be between 5 and 10

0
11
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 5  5  5  5]
 [ 6  7  8  9]
 [10 10 10 10]]


## numpy 索引

In [5]:
A = np.arange(3,15).reshape(3,4)
print(A[2]) # 第三行结果
print(A[1][2]) # 第二行第三列结果
print(A[:,1]) # 第二列结果

for row in A:
    print(row) # 每一行结果

for column in A.T:
    print(column) # 每一列结果 

for element in A.flat:
    print(element) # 每一个元素结果 

[11 12 13 14]
9
[ 4  8 12]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
3
4
5
6
7
8
9
10
11
12
13
14


## numpy array 合并

In [6]:
A = np.array([1,1,1])
B = np.array([2,2,2])
C = np.vstack((A,B)) # 合并A和B为一个2x3的数组
D = np.hstack((A,B)) # 合并A和B为一个1x6的数组
print(C)
print(D)

A = A[:, np.newaxis] # 将A转换为一个3x1的列向量
B = B[:, np.newaxis] # 将B转换为一个3x1的列向量
E = np.concatenate((A,B), axis=0) # 沿着第0轴（行）合并A和B
F = np.concatenate((A,B), axis=1) # 沿着第1轴（列）合并A和B
print(E)
print(F)    

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]


## array 分割

In [7]:
A = np.arange(12).reshape(3,4)

print(np.split(A,2,axis=1)) # 将A沿着第1轴（列）分成2个子数组
print(np.split(A,3,axis=0)) # 将A沿着第0轴（行）分成3个子数组
print(np.array_split(A,3,axis=1)) # 将A沿着第1轴（列）分成3个子数组，如果不能平均分割，则最后一个子数组会包含剩余的元素
print(np.vsplit(A,3)) # 将A沿着第0轴（行）分成3个子数组
print(np.hsplit(A,2)) # 将A沿着第1轴（列）分成2个子数组

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


## copy & deep copy

In [8]:
a = np.array([1,2,3])
b = a
print(a is b) # True, a和b引用同一个对象
c = a.copy() # 创建a的一个副本
print(a is c) # False, a和c引用不同的对象

True
False
